# Generated by Django 5.1.4 on 2025-06-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='api_key',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='source_type',
            field=models.CharField(default='newsapi', max_length=50),
        ),
        migrations.AlterField(
            model_name='source',
            name='link',
            field=models.URLField(max_length=1024),
        ),
    ]
