# Generated by Django 5.1.4 on 2025-06-09 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedarticle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile'),
        ),
    ]
